version: '3'

services:
  db-postgres-nomaders:
    image: postgres:alpine
    ports:
      - "5435:5432"
    container_name: "db-postgres-nomaders"
    restart: always
    volumes:
      - ./db-backup:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpassword

volumes:
  db-backup: